services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      NODE_ENV: production
    volumes:
      - ./auth-service/db.sqlite:/tmp/db.sqlite
    ports:
      - "3001:3000"   # Expose container 3000 as host 3001 (or just use 3000:3000)

  game-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      NODE_ENV: production
    ports:
      - "3002:3000"   # Expose container 3000 as host 3002 (or adjust as needed)

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - game-service
      - auth-service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
