version: '3.8'

services:
  auth-service:
    build:
      context: ../backend/auth-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID:-default_client_id}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET:-default_client_secret}
      JWT_SECRET: ${JWT_SECRET:-default_jwt_secret}
    ports:
      - "3001:3001"
    volumes:
      - auth_data:/app/db
    restart: unless-stopped

  game-service:
    build:
      context: ../backend/game-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "3002:8080"
    depends_on:
      - auth-service
    restart: unless-stopped

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - game-service
    restart: unless-stopped

volumes:
  auth_data:
